project_id = "qsmswvhfqaeebhxtfqwh"

[functions.send-sms]
verify_jwt = false

[functions.send-push]
verify_jwt = false

[functions.agora-token]
verify_jwt = true

[functions.call-push]
verify_jwt = true
