import 'package:wechat_flutter/generated/i18n.dart';

/// Tradução de textos que estão fixos em chinês no código.
/// Os textos em chinês continuam sendo usados como "chave" da lógica do app;
/// só a EXIBIÇÃO passa por aqui. Se o idioma não for pt-BR, ou se o texto
/// não estiver no dicionário, o texto original é devolvido sem alteração.
String trZh(String text) {
  if (S.current is! $pt_BR) return text;
  return _ptBr[text] ?? text;
}

const Map<String, String> _ptBr = <String, String>{
  '消息': 'Mensagens',
  '通讯录': 'Contatos',
  '发现': 'Descobrir',
  '我': 'Eu',
  '微信': 'WeChat',
  '支付': 'Pagamentos',
  '收藏': 'Favoritos',
  '相册': 'Álbum',
  '卡片': 'Cartões',
  '表情': 'Emojis',
  '设置': 'Configurações',
  '退出登录': 'Sair da conta',
  '朋友圈': 'Momentos',
  '扫一扫': 'Escanear',
  '摇一摇': 'Agitar',
  '看一看': 'Ver agora',
  '搜一搜': 'Pesquisar',
  '附近的人': 'Pessoas por perto',
  '漂流瓶': 'Garrafa à deriva',
  '附近的餐厅': 'Restaurantes por perto',
  '购物': 'Compras',
  '游戏': 'Jogos',
  '小程序': 'Mini programas',
  '新的朋友': 'Novos amigos',
  '群聊': 'Grupos',
  '标签': 'Etiquetas',
  '公众号': 'Contas oficiais',
  '无联系人': 'Nenhum contato',
  '无会话消息': 'Nenhuma conversa',
  '发起群聊': 'Criar grupo',
  '添加朋友': 'Adicionar amigo',
  '收付款': 'Pagar e receber',
  '帮助与反馈': 'Ajuda e feedback',
  '标为已读': 'Marcar como lida',
  '标为未读': 'Marcar como não lida',
  '置顶聊天': 'Fixar conversa',
  '删除该聊天': 'Excluir conversa',
  '置顶公众号': 'Fixar conta oficial',
  '取消关注': 'Deixar de seguir',
  '微信号：': 'ID do WeChat: ',
  '微信号': 'ID do WeChat',
  '个人信息': 'Informações pessoais',
  '头像': 'Foto de perfil',
  '昵称': 'Apelido',
  '二维码名片': 'Cartão com QR code',
  '我的地址': 'Meu endereço',
  '更多': 'Mais',
  '个性签名': 'Assinatura',
  '更改名字': 'Alterar nome',
  '保存': 'Salvar',
  '好名字可以让你的朋友更容易记住你': 'Um bom nome ajuda seus amigos a lembrarem de você',
  '输入的内容不能为空': 'O conteúdo não pode estar vazio',
  '输入的内容太长了': 'O conteúdo é muito longo',
  '设置名字成功': 'Nome alterado com sucesso',
  '设置名字失败': 'Falha ao alterar o nome',
  '服务器正在调整，敬请期待': 'Servidor em ajuste, aguarde',
  '微信号/手机号': 'ID do WeChat / celular',
  '该用户不存在': 'Usuário não encontrado',
  '雷达加朋友': 'Radar de amigos',
  '添加身边的朋友': 'Adicionar amigos por perto',
  '面对面建群': 'Criar grupo presencial',
  '与身边的朋友进入同一个群聊': 'Entre no mesmo grupo com quem está por perto',
  '扫描二维码名片': 'Escanear cartão QR',
  '手机联系人': 'Contatos do celular',
  '添加或邀请通讯录中的朋友': 'Adicione ou convide amigos da agenda',
  '获取更多资讯和服务': 'Receba mais notícias e serviços',
  '企业微信联系人': 'Contatos do WeCom',
  '通过手机号搜索企业微信用户': 'Buscar usuários do WeCom pelo celular',
  '添加手机联系人': 'Adicionar contatos do celular',
  '敬请期待': 'Em breve',
  '未知': 'Desconhecido',
  '这是我的签名': 'Esta é a minha assinatura',
  '添加到通讯录': 'Adicionar aos contatos',
  '验证申请': 'Pedido de verificação',
  '你需要发送验证申请，等对方通过': 'Envie um pedido de verificação e aguarde a aprovação',
  '为朋友设置备注': 'Definir apelido para o amigo',
  '设置朋友圈和视频动态权限': 'Definir permissões de Momentos e vídeos',
  '发送': 'Enviar',
  '设置备注和标签': 'Definir apelido e etiquetas',
  '发消息': 'Enviar mensagem',
  '音视频通话': 'Chamada de voz/vídeo',
  '更多信息': 'Mais informações',
  '备注': 'Apelido',
  '完成': 'Concluir',
  '所有标签': 'Todas as etiquetas',
  '您暂时没有标签': 'Você ainda não tem etiquetas',
  '选择一个群': 'Selecione um grupo',
  '创建群组成功': 'Grupo criado com sucesso',
  '创建失败': 'Falha ao criar',
  '暂无群聊': 'Nenhum grupo',
  '选择群聊': 'Selecionar grupo',
  '您没有关注任何公众号': 'Você não segue nenhuma conta oficial',
  '确定': 'OK',
  '取消': 'Cancelar',
  '删除': 'Excluir',
  '搜索': 'Pesquisar',
  '选择联系人': 'Selecionar contatos',
  '请选择要添加的成员': 'Selecione os membros a adicionar',
  '群公告': 'Aviso do grupo',
  '请编辑群公告': 'Edite o aviso do grupo',
  '暂无公告': 'Sem avisos',
  '默认': 'Padrão',
  '查看全部群成员': 'Ver todos os membros',
  '群聊名称': 'Nome do grupo',
  '群二维码': 'QR code do grupo',
  '群管理': 'Gerenciar grupo',
  '聊天置顶': 'Fixar conversa',
  '保存到通讯录': 'Salvar nos contatos',
  '我在群里的昵称': 'Meu apelido no grupo',
  '显示群成员昵称': 'Mostrar apelidos dos membros',
  '失败': 'Falha',
  '成功': 'Sucesso',
  '解散群聊成功': 'Grupo dissolvido',
  '退出成功': 'Você saiu do grupo',
  '确定要退出本群吗？': 'Deseja mesmo sair deste grupo?',
  '删除并退出': 'Excluir e sair',
  '修改群聊名称': 'Alterar nome do grupo',
  '我在本群的昵称': 'Meu apelido neste grupo',
  '请输入内容': 'Digite o conteúdo',
  '群聊的备注仅自己可见': 'A observação do grupo só é visível para você',
  '填入': 'Preencher',
  '修改群聊名称后，将在群内通知其他成员': 'Ao alterar o nome, os outros membros serão avisados',
  '昵称修改后，只会在此群内显示，群内成员都可以看见。': 'O apelido aparece só neste grupo e todos os membros podem vê-lo.',
  '默认昵称': 'Apelido padrão',
  '无名氏': 'Anônimo',
  '无头像': 'Sem foto',
  '昵称：': 'Apelido: ',
  '地区：': 'Região: ',
  '聊天信息': 'Informações da conversa',
  '消息免打扰': 'Não perturbe',
  '强提醒': 'Alerta forte',
  '查找聊天记录': 'Buscar no histórico',
  '设置当前聊天背景': 'Definir plano de fundo',
  '清空聊天记录': 'Limpar histórico',
  '确定删除群的聊天记录吗？': 'Excluir o histórico do grupo?',
  '清空': 'Limpar',
  '投诉': 'Denunciar',
  '拍摄': 'Câmera',
  '视频通话': 'Chamada de vídeo',
  '位置': 'Localização',
  '红包': 'Envelope vermelho',
  '转账': 'Transferência',
  '语音输入': 'Entrada de voz',
  '我的收藏': 'Meus favoritos',
  '名片': 'Cartão de contato',
  '文件': 'Arquivo',
  '聊天背景': 'Plano de fundo',
  '选择背景图': 'Escolher imagem de fundo',
  '从手机相册选择': 'Escolher da galeria',
  '拍一张': 'Tirar foto',
  '切换完毕': 'Alterado',
  '复制': 'Copiar',
  '转发': 'Encaminhar',
  '撤回': 'Recolher',
  '复制消息到剪贴板': 'Copiar mensagem',
  '删除消息': 'Excluir mensagem',
  '按住说话': 'Segure para falar',
  '手指上滑,取消发送': 'Deslize para cima para cancelar',
  '手指上滑，取消发送': 'Deslize para cima para cancelar',
  '松开结束': 'Solte para terminar',
  '松开手指,取消发送': 'Solte para cancelar',
  '松开手指，取消发送': 'Solte para cancelar',
  '取消发送': 'Cancelar envio',
  '进行发送': 'Enviando',
  '发送中': 'Enviando',
  '未知消息': 'Mensagem desconhecida',
  '[图片]': '[Imagem]',
  '[语音消息]': '[Mensagem de voz]',
  '[视频]': '[Vídeo]',
  '[系统消息] 新人入群': '[Sistema] Novo membro no grupo',
  '[系统消息] 有人退出群聊': '[Sistema] Alguém saiu do grupo',
  '[系统消息] 群资料变更': '[Sistema] Dados do grupo alterados',
  '[系统消息] 群员修改资料': '[Sistema] Membro alterou o perfil',
  '[系统消息]': '[Sistema]',
  '[未知消息]': '[Mensagem desconhecida]',
  '微信红包': 'Envelope vermelho do WeChat',
  '恭喜发财，大吉大利': 'Muita prosperidade e sorte!',
  '文字为空': 'Texto vazio',
  '播放中': 'Reproduzindo',
  '加载中': 'Carregando',
  '搜索：': 'Pesquisar: ',
  '搜一搜：': 'Pesquisar: ',
  '小程序、公众号、文章、朋友圈、和表情等': 'Mini programas, contas oficiais, artigos, Momentos, emojis e mais',
  '文章': 'Artigos',
  '音乐': 'Músicas',
  '搜索指定内容': 'Pesquisar conteúdo',
  '温馨提示：': 'Aviso: ',
  '更新': 'Atualizar',
  '下载超时': 'Tempo de download esgotado',
  '你确定要删除此联系人吗': 'Deseja mesmo excluir este contato?',
  '删除联系人': 'Excluir contato',
  '把她推荐给朋友': 'Recomendar a amigos',
  '设为星标好友': 'Marcar como favorito',
  '加入黑名单': 'Adicionar à lista negra',
  '添加到桌面': 'Adicionar à tela inicial',
  '换个样式': 'Mudar estilo',
  '保存到手机': 'Salvar no celular',
  '扫描二维码': 'Escanear QR code',
  '重置二维码': 'Redefinir QR code',
  '赞': 'Curtir',
  '评论': 'Comentar',
  '从相册选择': 'Escolher da galeria',
  '发表': 'Publicar',
  '所在位置': 'Localização',
  '谁可以看': 'Quem pode ver',
  '提醒谁看': 'Avisar quem',
  '保留此次编辑？': 'Manter esta edição?',
  '不保留': 'Não manter',
  '保留': 'Manter',
  '已添加': 'Adicionado',
  '添加': 'Adicionar',
  '不让他(她)看': 'Não deixar ver',
  '推荐好友': 'Amigos sugeridos',
  '查看提示': 'Ver dica',
  '感谢支持': 'Obrigado pelo apoio',
  '金融理财': 'Finanças',
  '信用卡还款': 'Pagar cartão de crédito',
  '理财通': 'Investimentos',
  '生活服务': 'Serviços do dia a dia',
  '手机充值': 'Recarga de celular',
  '生活缴费': 'Contas e tarifas',
  'Q币充值': 'Recarga de Q Coins',
  '城市服务': 'Serviços da cidade',
  '腾讯公益': 'Tencent Filantropia',
  '医疗健康': 'Saúde',
  '防疫健康码': 'Código de saúde',
  '交通出行': 'Transporte',
  '出行服务': 'Serviços de viagem',
  '火车票机票': 'Trem e passagens aéreas',
  '滴滴出行': 'Didi (carona)',
  '酒店': 'Hotéis',
  '购物消费': 'Compras',
  '京东购物': 'JD.com',
  '美团外卖': 'Meituan Delivery',
  '电影演出赛事': 'Cinema e eventos',
  '美团团购': 'Meituan Ofertas',
  '拼多多': 'Pinduoduo',
  '蘑菇街女装': 'Moda feminina Mogu',
  '唯品会特卖': 'Vipshop Ofertas',
  '转转二手': 'Zhuanzhuan (usados)',
  '贝壳找房': 'Beike Imóveis',
  '钱包': 'Carteira',
};
